### ISSUE TITLE
Unable to evaluate query Exception

### ISSUE THREAD

**Issue by AntoineGauthier** [rappen/CRMWinForm#14]
Hi there,

_This might be related to the issue #246._ 

I recently updated to 1.2019.3.3 and later 1.2019.3.4 and in both cases I can't use your plugin anymore.

I now face a System.ServiceModel.FaultException saying 
1. "Unable to evaluate query"
2. "The type EntityMetadata does not have a property named LogicalCollectionName"

> System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Unable to evaluate query (Fault Detail is equal to Exception details: 
> ErrorCode: 0x80044183
> Message: Unable to evaluate query
> TimeStamp: 2019-03-11T09:47:02.7272355Z
> --
> Exception details: 
> ErrorCode: 0x80044183
> Message: Unable to evaluate query
> TimeStamp: 2019-03-11T09:47:02.7272355Z
> --
> Exception details: 
> ErrorCode: 0x80044183
> Message: The type EntityMetadata does not have a property named LogicalCollectionName
> TimeStamp: 2019-03-11T09:47:02.7272355Z
> --
> ).

This happens when I try to run a query or when the query gets re evaluated like when I uncomment sections of the query for example.

Here is a screenshot if that helps in any way:

![image](https://user-images.githubusercontent.com/10197231/54186021-ada65900-44aa-11e9-9f87-5370381bdc22.png)

Let me know if I can be of any more assistance regarding the diagnostic of the issue.

Regards,

Antoine

**Comment by rappen** [comment]
I have just published an update, please try the latest which should be version 1.2019.3.5 and let me know if it works for you!

**Comment by AntoineGauthier** [comment]
> 
> 
> I have just published an update, please try the latest which should be version 1.2019.3.5 and let me know if it works for you!

It's working great! thanks a lot!
