### ISSUE TITLE
Export Results

### ISSUE THREAD

**Issue by zenecamickeyd** [rappen/CRMWinForm#16]
Provide a way of exporting FetchXmlBuilder results so that the data for multi-line text fields is enclosed with quotes.  Copying and pasting the results grid into Excel creates new rows where CR/LF appears in multi-line text fields.  Or better yet, provide a mechanism for exporting directly to Excel.

**Comment by rappen** [comment]
Transferred manually to https://github.com/jamesnovak/xrmtb.XrmToolBox.Controls/issues/12
